<header class="entry-header">

<h1 class="entry-title">Disclaimer</h1>
</header><!-- .entry-header -->

<div class="entry-content">
<p><span style="color: #615f5a;">THE MATERIAL EMBODIED IN THIS SOFTWARE IS PROVIDED TO YOU “AS-IS” AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED, OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL THE CPSC OR THE UNITED STATES GOVERNMENT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT, SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER, INCLUDING WITHOUT LIMITATION, LOSS OF PROFIT, LOSS OF USE, SAVINGS OR REVENUE, OR THE CLAIMS OF THIRD PARTIES, WHETHER OR NOT DOC OR THE U.S. GOVERNMENT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS, HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE POSSESSION, USE, OR PERFORMANCE OF THIS SOFTWARE.</span></p>


<form method="post" action="">
  <input type="submit" value="Agree" name="agreed"/> 
  <input type="button"  value="I Do Not Agree" name="notagreed"/> 
</form> 



</div><!-- .entry-content -->

<footer class="entry-meta">
</footer><!-- .entry-meta -->



